location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: false
    registries:
    - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
      identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: applicationinsights-connection-string
        value: '{{ .Env.INSIGHTS_APPINSIGHTSCONNECTIONSTRING }}'
      - name: connectionstrings--codebreakerevents
        value: '{{ .Env.CODEBREAKEREVENTS_EVENTHUBSENDPOINT }}'
      - name: connectionstrings--signalr
        value: Endpoint=https://{{ .Env.SIGNALR_HOSTNAME }};AuthType=azure
  template:
    containers:
    - image: {{ .Image }}
      name: live
      env:
      - name: AZURE_CLIENT_ID
        value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
      - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
        value: "true"
      - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
        value: in_memory
      - name: APPLICATIONINSIGHTS_CONNECTION_STRING
        secretRef: applicationinsights-connection-string
      - name: ConnectionStrings__codebreakerevents
        secretRef: connectionstrings--codebreakerevents
      - name: ConnectionStrings__signalr
        secretRef: connectionstrings--signalr
    scale:
      minReplicas: 1
tags:
  azd-service-name: live
  aspire-resource-name: live
